- name: Copy and Start Go on Linux Server
  hosts: webservers
  become: yes
  vars_files:
    - ~/.ansible_vault
  tasks:
    - name: Copy Go Binary
      copy:
        src: ../todoapp
        dest: /home/moni
        mode: "0755"

    - name: Start Go Application
      command: ./todoapp
